export const FETCH_FOODS = "FETCH_FOODS";
export const FILTER_FOODS_BY_TYPES = "FILTER_FOODS_BY_TYPES";
export const ORDER_FOODS_BY_PRICE = "ORDER_FOODS_BY_PRICE";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CREATE_ORDER = "CREATE_ORDER";
export const CLEAR_ORDER = "CLEAR_ORDER";
export const CLEAR_CART = "CLEAR_CART";